services:
    mysql:
        image: mariadb:latest
        environment:
            MARIADB_ROOT_PASSWORD: :B>ta!RY^2S<ew%.hq^mk#Df?6ew>qrT
        expose:
            - "3306"
        ports:
            - "3306:3306"
        volumes:
            # - ./database/:/docker-entrypoint-initdb.d/
            - db_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "test" ,"-d", "var/lib/mysql"]
    express:
        image: ktbloomq/senior-project-backend:1.0
        build:
            context: .
            dockerfile: backend/dockerfile
        depends_on:
            mysql:
                condition: service_healthy
        environment:
            - MY_SQL_DB_HOST=mysql
        expose:
            - "5000"
        command: "npm run dev"
    next:
        image: ktbloomq/senior-project-frontend:1.0
        build:
            context: .
            dockerfile: frontend/dockerfile
        depends_on:
            - express
        environment:
            - API_HOST=express
        expose:
            - "3000"
        ports:
            - "80:3000"
        command: "npm run dev"
volumes:
    db_data: